name: gen
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1 
  flutter_svg: ^2.0.7
  lottie: ^2.7.0
  envied: ^0.5.0
  equatable: ^2.0.5
  vexana: ^3.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  envied_generator: ^0.5.3
  json_serializable: ^6.7.1   
  flutter_gen_runner: ^5.4.0 


flutter_gen:
  output: lib/src/asset/
  integrations:
    flutter_svg: true
    lottie: true

  colors:
    inputs: 
      - assets/color/colors.xml

  assets:
    outputs:
      package_parameter_enabled: true

flutter: 
  assets:
    - assets/color/
    - assets/lottie/
    - assets/icons/
    - assets/images/
    - assets/fonts/
#
