name: architecture_template
# description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
homepage: 'none'

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  common:
    path: module/common
  core:
    path: module/core
  gen: 
    path: module/gen
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  easy_logger: ^0.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5

  get_it: ^7.6.7
  auto_route: ^7.8.4

  google_fonts: ^6.1.0
  kartal: ^3.4.4
  logger: ^2.0.2+1
  vexana: ^3.5.4
  widgets:
    path: module/widgets
  dio: ^5.4.0
  smooth_page_indicator: ^1.1.0

# dependency_overrides:
#   # flutter_lints: ^1.0.0
dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
  auto_route_generator: ^7.3.2 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_version: 21 # android min sdk min:16, default: 21
  remove_aplha_ios: true # default: false


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
